/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HttpServer {
  constructor()
  onRequest(callback: RequestTsfn): void
  onWsEvent(callback: WsEventTsfn): void
  listen(port: number, hostname?: string | undefined | null): Promise<ServerInfo>
  close(closeActiveConnections?: boolean | undefined | null): Promise<void>
  sendResponse(requestId: number, response: ResponseData): void
  sendResponseText(requestId: number, status: number, headers: Array<string>, body: string): void
  sendResponseBuffer(requestId: number, status: number, headers: Array<string>, body: Array<number>): void
  pendingCount(): number
  wsSend(connectionId: string, message: string): number
  wsSendBinary(connectionId: string, data: Array<number>): number
  wsClose(connectionId: string): void
  wsConnectionCount(): number
  wsConnectionIds(): Array<string>
  wsSubscribe(connectionId: string, topic: string): void
  wsUnsubscribe(connectionId: string, topic: string): void
  wsIsSubscribed(connectionId: string, topic: string): boolean
  wsPublish(connectionId: string, topic: string, message: string): number
  serverPublish(topic: string, message: string): number
}

export interface RequestCall {
  request: RequestData
  requestId: number
}

export interface RequestData {
  method: string
  url: string
  path: string
  headers: Array<string>
  body?: Array<number>
  remoteAddr: string
}

export interface ResponseData {
  status: number
  headers: Array<string>
  body?: Array<number>
  upgrade?: boolean
  connectionId?: string
}

export interface ServerInfo {
  port: number
  address: string
}

export interface WsEvent {
  eventType: string
  connectionId: string
  text?: string
  binary?: Array<number>
  error?: string
  code?: number
  reason?: string
  remoteAddr?: string
}
