/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HttpServer {
  constructor()
  /**
   * Set a Validator instance for automatic request validation.
   * When set, the server will validate body/query/params before calling JS.
   */
  setValidator(validator: Validator): void
  /** Enable/disable automatic validation before JS callback. */
  setAutoValidate(enabled: boolean): void
  onRequest(callback: (data: RequestData) => void): void
  onWsEvent(callback: (event: WsEvent) => void): void
  listen(port: number, hostname?: string | undefined | null): Promise<ServerInfo>
  close(closeActiveConnections?: boolean | undefined | null): Promise<void>
  sendResponse(requestId: number, response: ResponseData): void
  sendResponseText(requestId: number, status: number, headers: Array<string>, body: string): void
  sendResponseBuffer(requestId: number, status: number, headers: Array<string>, body: Array<number>): void
  /** Direct buffer path — accepts Uint8Array / Buffer (zero-copy bytes from JS). */
  sendResponseBufferDirect(requestId: number, status: number, headers: Array<string>, body?: Buffer | undefined | null): void
  /** Zero-copy submission of a NativeResponse. Takes data via std::mem::take. */
  submitNativeResponse(requestId: number, response: NativeResponse): void
  /**
   * Binary protocol: buffer contains [status:u16 LE][header_section_len:u32 LE] +
   * [num_strings:u32 LE] + alternating (key_len:u32 LE, key_bytes, val_len:u32 LE, val_bytes) + body
   */
  sendResponseRaw(requestId: number, buf: Buffer): void
  pendingCount(): number
  requestIp(requestId: number): SocketAddress | null
  wsSend(connectionId: string, message: string): number
  wsSendBinary(connectionId: string, data: Array<number>): number
  wsClose(connectionId: string): void
  wsConnectionCount(): number
  wsConnectionIds(): Array<string>
  wsSubscribe(connectionId: string, topic: string): void
  wsUnsubscribe(connectionId: string, topic: string): void
  wsIsSubscribed(connectionId: string, topic: string): boolean
  wsPublish(connectionId: string, topic: string, message: string): number
  serverPublish(topic: string, message: string): number
  get port(): number
  get hostname(): string
  get url(): string
  upgrade(requestId: number): string | null
  stop(closeActiveConnections?: boolean | undefined | null): Promise<void>
}

/**
 * Rust-native response builder. Data stays in Rust memory — no JS object overhead.
 * Use with `HttpServer::submit_native_response` for zero-copy submission.
 */
export declare class NativeResponse {
  constructor()
  status(code: number): this
  header(name: string, value: string): this
  text(data: string): this
  json(data: string): this
  html(data: string): this
  setBodyBuffer(data: Buffer): this
  redirect(url: string, status?: number | undefined | null): this
  reset(): this
}

export declare class Validator {
  constructor()
  /**
   * Register a validation schema for a route.
   * route_key format: "METHOD:/path" (e.g. "POST:/users")
   * schema_json: JSON string with { body?, query?, params? } definitions
   */
  addSchema(routeKey: string, schemaJson: string): void
  /**
   * Validate a JSON body string against the registered schema.
   * Parses JSON in Rust (from string) and validates against compiled schema.
   */
  validateBody(routeKey: string, bodyJson: string): ValidationResult
  /**
   * Validate a JSON body from raw bytes (zero-copy). Avoids string conversion.
   * This is the fastest path — parses directly from Uint8Array/Buffer.
   */
  validateBodyBytes(routeKey: string, body: Buffer): ValidationResult
  /**
   * Validate a pre-serialized JSON body value (string).
   * Alias for validate_body — accepts the body as a JSON string.
   */
  validateBodyValue(routeKey: string, bodyJson: string): ValidationResult
  /** Validate query parameters against the registered schema. */
  validateQuery(routeKey: string, query: Record<string, string>): ValidationResult
  /** Validate path parameters against the registered schema. */
  validateParams(routeKey: string, params: Record<string, string>): ValidationResult
  /** Check if a schema exists for a route. */
  hasSchema(routeKey: string): boolean
  /** Remove a schema for a route. */
  removeSchema(routeKey: string): boolean
  /** Clear all schemas. */
  clear(): void
  /** Get the number of registered schemas. */
  schemaCount(): number
}

export interface RequestData {
  method: string
  url: string
  path: string
  headers: Array<string>
  /** Exposed to JS as a zero-copy `Uint8Array`. */
  body?: Array<number>
  remoteAddr: string
  requestId: number
  /**
   * Pre-parsed JSON body serialized as string. Null if body is not JSON or absent.
   * JS can do JSON.parse(parsedBody) — faster than req.clone().text() + JSON.parse()
   */
  parsedBody?: string
  /** Query parameters parsed from URL in Rust. */
  queryParams?: Record<string, string>
}

export interface ResponseData {
  status: number
  headers: Array<string>
  /** Accepted from JS as `Uint8Array` OR `number[]` via the adapter. */
  body?: Array<number>
  upgrade?: boolean
  connectionId?: string
}

export interface ServerInfo {
  port: number
  address: string
}

export interface SocketAddress {
  address: string
  family: string
  port: number
}

export interface ValidationErr {
  field: string
  message: string
  code: string
}

export interface ValidationResult {
  success: boolean
  errors?: Array<ValidationErr>
  /** Serialized validated data (JSON string). Null if validation failed or no data. */
  data?: string
}

export interface WsEvent {
  eventType: string
  connectionId: string
  text?: string
  /** Exposed to JS as a zero-copy `Uint8Array`. */
  binary?: Array<number>
  error?: string
  code?: number
  reason?: string
  remoteAddr?: string
}
