/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HttpServer {
  constructor()
  onRequest(callback: (data: RequestData) => void): void
  onWsEvent(callback: (event: WsEvent) => void): void
  listen(port: number, hostname?: string | undefined | null): Promise<ServerInfo>
  close(closeActiveConnections?: boolean | undefined | null): Promise<void>
  sendResponse(requestId: number, response: ResponseData): void
  sendResponseText(requestId: number, status: number, headers: Array<string>, body: string): void
  sendResponseBuffer(requestId: number, status: number, headers: Array<string>, body: Array<number>): void
  /**
   * Binary protocol: buffer contains [status:u16 LE][header_section_len:u32 LE] +
   * [num_strings:u32 LE] + alternating (key_len:u32 LE, key_bytes, val_len:u32 LE, val_bytes) + body
   */
  sendResponseRaw(requestId: number, buf: Buffer): void
  pendingCount(): number
  requestIp(requestId: number): SocketAddress | null
  wsSend(connectionId: string, message: string): number
  wsSendBinary(connectionId: string, data: Array<number>): number
  wsClose(connectionId: string): void
  wsConnectionCount(): number
  wsConnectionIds(): Array<string>
  wsSubscribe(connectionId: string, topic: string): void
  wsUnsubscribe(connectionId: string, topic: string): void
  wsIsSubscribed(connectionId: string, topic: string): boolean
  wsPublish(connectionId: string, topic: string, message: string): number
  serverPublish(topic: string, message: string): number
}

export interface RequestData {
  method: string
  url: string
  path: string
  headers: Array<string>
  /** Exposed to JS as a zero-copy `Uint8Array`. */
  body?: Array<number>
  remoteAddr: string
  requestId: number
}

export interface ResponseData {
  status: number
  headers: Array<string>
  /** Accepted from JS as `Uint8Array` OR `number[]` via the adapter. */
  body?: Array<number>
  upgrade?: boolean
  connectionId?: string
}

export interface ServerInfo {
  port: number
  address: string
}

export interface SocketAddress {
  address: string
  family: string
  port: number
}

export interface WsEvent {
  eventType: string
  connectionId: string
  text?: string
  /** Exposed to JS as a zero-copy `Uint8Array`. */
  binary?: Array<number>
  error?: string
  code?: number
  reason?: string
  remoteAddr?: string
}
