/**
 * napi-router adapter — Bun-compatible serve() API
 *
 * Wraps the native HttpServer (NAPI binding) in a high-level API that mirrors
 * Bun.serve() so the same application code runs on Node.js, Bun, and Deno.
 *
 * DO NOT modify index.js / index.d.ts — those are auto-generated by napi-rs build.
 */

// ---------------------------------------------------------------------------
// Dynamic import of the native binding (works in ESM and CJS)
// ---------------------------------------------------------------------------
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const _require = createRequire(import.meta.url);

/** @type {{ HttpServer: typeof import('../index.js').HttpServer }} */
const native = _require(resolve(__dirname, '../index.js'));
const { HttpServer } = native;

// ---------------------------------------------------------------------------
// ServerHandle — returned by serve(), mirrors Bun's server object
// ---------------------------------------------------------------------------

class ServerHandle {
  /** @type {import('../index.js').HttpServer} */
  #raw;
  /** @type {number} */
  #port;
  /** @type {string} */
  #hostname;
  /** @type {boolean} */
  #stopped = false;

  /**
   * @param {import('../index.js').HttpServer} raw
   * @param {number} port
   * @param {string} hostname
   */
  constructor(raw, port, hostname) {
    this.#raw = raw;
    this.#port = port;
    this.#hostname = hostname;
  }

  /** Bound port (may differ from requested when port=0 was used) */
  get port() { return this.#port; }

  /** Bound hostname */
  get hostname() { return this.#hostname; }

  /** URL string for the server root */
  get url() { return `http://${this.#hostname}:${this.#port}/`; }

  /** Number of requests currently waiting for a fetch-handler response */
  get pendingRequests() { return this.#raw.pendingCount(); }

  /** Number of open WebSocket connections */
  get pendingWebSockets() { return this.#raw.wsConnectionCount(); }

  /**
   * Stop the server. Safe to call multiple times.
   * @param {boolean} [closeActiveConnections=false]
   */
  stop(closeActiveConnections = false) {
    if (this.#stopped) return;
    this.#stopped = true;
    this.#raw.close().catch(() => {});
  }

  // ── WebSocket helpers (mirrors Bun's ServerWebSocket API surface) ────────

  /**
   * Send a text message to a specific WebSocket connection.
   * @param {string} connectionId
   * @param {string} message
   */
  sendToWs(connectionId, message) {
    return this.#raw.wsSend(connectionId, message);
  }

  /**
   * Send binary data to a specific WebSocket connection.
   * @param {string} connectionId
   * @param {number[]} data
   */
  sendBinaryToWs(connectionId, data) {
    return this.#raw.wsSendBinary(connectionId, data);
  }

  /**
   * Close a specific WebSocket connection.
   * @param {string} connectionId
   */
  closeWs(connectionId) {
    return this.#raw.wsClose(connectionId);
  }

  /** All currently open WebSocket connection IDs */
  get wsConnectionIds() {
    return this.#raw.wsConnectionIds();
  }

  // Allow instanceof checks against a named class
  get [Symbol.toStringTag]() { return 'ServerHandle'; }
}

// ---------------------------------------------------------------------------
// Request bridge — converts the native RequestData into a Web API Request
// ---------------------------------------------------------------------------

/**
 * @param {import('../index.js').RequestData} data
 * @param {string} baseUrl  e.g. "http://0.0.0.0:9999"
 * @returns {Request}
 */
function toWebRequest(data, baseUrl) {
  // The URL from hyper may be a bare path; prefix the origin so it is valid.
  const url = data.url.startsWith('http') ? data.url : `${baseUrl}${data.url}`;

  const headers = new Headers();
  for (const [k, v] of Object.entries(data.headers ?? {})) {
    headers.set(k, v);
  }

  const init = {
    method: data.method,
    headers,
  };

  if (data.body != null && data.body.length > 0 && data.method !== 'GET' && data.method !== 'HEAD') {
    init.body = data.body;
  }

  return new Request(url, init);
}

// ---------------------------------------------------------------------------
// Response bridge — converts a Web API Response into native ResponseData
// ---------------------------------------------------------------------------

/**
 * @param {Response} response
 * @returns {Promise<import('../index.js').ResponseData>}
 */
async function fromWebResponse(response) {
  const headers = {};
  response.headers.forEach((value, key) => {
    headers[key] = value;
  });

  let body = null;
  try {
    body = await response.text();
  } catch {
    body = '';
  }

  return {
    status: response.status,
    headers,
    body,
  };
}

// ---------------------------------------------------------------------------
// WebSocket bridge — wraps the native ws event callbacks in Bun-like handlers
// ---------------------------------------------------------------------------

/**
 * Build a thin "ws" proxy object that mirrors Bun's ServerWebSocket interface.
 * @param {string} connectionId
 * @param {import('../index.js').HttpServer} raw
 * @returns {object}
 */
function makeWsProxy(connectionId, raw) {
  return {
    get id() { return connectionId; },
    send(msg) {
      if (typeof msg === 'string') return raw.wsSend(connectionId, msg);
      return raw.wsSendBinary(connectionId, Array.from(msg));
    },
    close(code, reason) {
      return raw.wsClose(connectionId);
    },
    get readyState() { return 1; /* OPEN */ },
  };
}

/**
 * Wire up a WebSocket handler from the user-supplied `websocket` option.
 *
 * @param {import('../index.js').HttpServer} raw
 * @param {ServeOptions['websocket']} wsHandlers
 */
function wireWebSocket(raw, wsHandlers) {
  if (!wsHandlers) return;

  raw.onWsEvent((event) => {
    const ws = makeWsProxy(event.connectionId, raw);

    switch (event.eventType) {
      case 'open':
        wsHandlers.open?.(ws);
        break;
      case 'message':
        if (event.text != null) {
          wsHandlers.message?.(ws, event.text);
        } else if (event.binary != null) {
          wsHandlers.message?.(ws, new Uint8Array(event.binary));
        }
        break;
      case 'close':
        wsHandlers.close?.(ws, event.code ?? 1000, event.reason ?? '');
        break;
      case 'error':
        wsHandlers.error?.(ws, new Error(event.error ?? 'WebSocket error'));
        break;
      case 'disconnect':
        wsHandlers.close?.(ws, event.code ?? 1000, event.reason ?? '');
        break;
    }
  });
}

// ---------------------------------------------------------------------------
// serve() — the main public API
// ---------------------------------------------------------------------------

/**
 * @typedef {object} ServeOptions
 * @property {number}  [port=3000]
 * @property {string}  [hostname='0.0.0.0']
 * @property {(req: Request, server: ServerHandle) => Response | Promise<Response>} fetch
 * @property {object}  [websocket]
 * @property {(ws: any) => void}                        [websocket.open]
 * @property {(ws: any, msg: string|Uint8Array) => void} [websocket.message]
 * @property {(ws: any, code: number, reason: string) => void} [websocket.close]
 * @property {(ws: any, err: Error) => void}            [websocket.error]
 * @property {(req: Request, server: ServerHandle) => Response | undefined} [websocket.upgrade]
 */

/**
 * Start an HTTP server with a Bun-compatible API.
 *
 * @param {ServeOptions} options
 * @returns {Promise<ServerHandle>}
 */
export async function serve(options) {
  const {
    port = 3000,
    hostname = '0.0.0.0',
    fetch: fetchHandler,
    websocket,
    error: errorHandler,
  } = options;

  if (typeof fetchHandler !== 'function') {
    throw new TypeError('serve(): options.fetch must be a function');
  }

  const raw = new HttpServer();
  let handle = null; // set after listen resolves

  // Register WebSocket handlers before listening
  wireWebSocket(raw, websocket);

  // Wire the request handler
  raw.onRequest(async ({ request: requestData, requestId }) => {
    const baseUrl = `http://${hostname}:${port}`;
    const webRequest = toWebRequest(requestData, baseUrl);

    let response;
    try {
      response = await fetchHandler(webRequest, handle);
      if (!(response instanceof Response)) {
        response = new Response('Internal Server Error: fetch handler must return a Response', { status: 500 });
      }
    } catch (err) {
      if (typeof errorHandler === 'function') {
        try {
          response = await errorHandler(err);
        } catch {
          response = new Response('Internal Server Error', { status: 500 });
        }
      } else {
        console.error('[napi-router] Unhandled error in fetch handler:', err);
        response = new Response('Internal Server Error', { status: 500 });
      }
    }

    const responseData = await fromWebResponse(response);
    raw.sendResponse(requestId, responseData);
  });

  const info = await raw.listen(port, hostname);
  handle = new ServerHandle(raw, info.port, info.address);
  return handle;
}

// ---------------------------------------------------------------------------
// tryServe() — non-throwing variant
// ---------------------------------------------------------------------------

/**
 * Like serve(), but returns `{ server, error }` instead of throwing on failure.
 *
 * @param {ServeOptions} options
 * @returns {Promise<{ server: ServerHandle | null, error: Error | null }>}
 */
export async function tryServe(options) {
  try {
    const server = await serve(options);
    return { server, error: null };
  } catch (err) {
    return { server: null, error: /** @type {Error} */ (err) };
  }
}

// ---------------------------------------------------------------------------
// Re-export raw binding types for advanced users
// ---------------------------------------------------------------------------

export { HttpServer };
export { ServerHandle as Server };
