/**
 * napi-router adapter — TypeScript types
 *
 * DO NOT edit index.d.ts — that file is auto-generated by napi-rs build.
 * These types describe the high-level adapter API exported from adapter/serve.js.
 */

import type { HttpServer } from '../index.js';
export type { HttpServer };

// ---------------------------------------------------------------------------
// WebSocket handler interface (mirrors Bun's websocket option)
// ---------------------------------------------------------------------------

export interface ServerWebSocket {
  /** Unique connection identifier assigned by napi-router */
  readonly id: string;
  /** Send a text message */
  send(message: string): Promise<void>;
  /** Send binary data */
  send(data: Uint8Array): Promise<void>;
  /** Close the connection */
  close(code?: number, reason?: string): Promise<void>;
  /** Always 1 (OPEN) while the handler is invoked */
  readonly readyState: number;
}

export interface WebSocketHandlers {
  /** Called when a new WebSocket connection is established */
  open?(ws: ServerWebSocket): void | Promise<void>;
  /** Called when a message is received */
  message?(ws: ServerWebSocket, message: string | Uint8Array): void | Promise<void>;
  /** Called when the connection closes */
  close?(ws: ServerWebSocket, code: number, reason: string): void | Promise<void>;
  /** Called on a WebSocket error */
  error?(ws: ServerWebSocket, error: Error): void | Promise<void>;
}

// ---------------------------------------------------------------------------
// ServerHandle — returned by serve()
// ---------------------------------------------------------------------------

export declare class Server {
  /** Bound port */
  readonly port: number;
  /** Bound hostname / IP */
  readonly hostname: string;
  /** Convenience URL string, e.g. "http://0.0.0.0:3000/" */
  readonly url: string;
  /** Number of in-flight requests awaiting a fetch-handler response */
  readonly pendingRequests: number;
  /** Number of open WebSocket connections */
  readonly pendingWebSockets: number;

  /** Stop the server. Safe to call multiple times. */
  stop(closeActiveConnections?: boolean): void;

  /** Send a text message to a specific WebSocket connection */
  sendToWs(connectionId: string, message: string): Promise<void>;
  /** Send binary data to a specific WebSocket connection */
  sendBinaryToWs(connectionId: string, data: number[]): Promise<void>;
  /** Close a specific WebSocket connection */
  closeWs(connectionId: string): Promise<void>;
  /** All currently open WebSocket connection IDs */
  readonly wsConnectionIds: string[];
}

// ---------------------------------------------------------------------------
// serve() options
// ---------------------------------------------------------------------------

export interface ServeOptions {
  /** TCP port to listen on. Defaults to 3000. */
  port?: number;
  /** Hostname / IP to bind. Defaults to "0.0.0.0". */
  hostname?: string;
  /**
   * Request handler — receives a standard Web API `Request` and must return a
   * `Response` (or a Promise that resolves to one).
   */
  fetch(request: Request, server: Server): Response | Promise<Response>;
  /**
   * WebSocket event handlers. Providing this object enables WebSocket support.
   */
  websocket?: WebSocketHandlers;
  /**
   * Optional error handler called when `fetch` throws.
   * Must return a `Response`. Falls back to a 500 if omitted.
   */
  error?(error: Error): Response | Promise<Response>;
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

/**
 * Start an HTTP server with a Bun-compatible `serve()` API.
 * Works in Node.js, Bun, and Deno.
 *
 * @example
 * ```ts
 * import { serve } from 'napi-router/adapter';
 *
 * const server = await serve({
 *   port: 3000,
 *   fetch(req) {
 *     return new Response('Hello!');
 *   },
 * });
 * console.log(`Listening on ${server.url}`);
 * ```
 */
export declare function serve(options: ServeOptions): Promise<Server>;

/**
 * Non-throwing variant of `serve()`.
 * Returns `{ server, error }` instead of throwing.
 *
 * @example
 * ```ts
 * const { server, error } = await tryServe({ port: 3000, fetch: handler });
 * if (error) console.error('Failed to start:', error);
 * ```
 */
export declare function tryServe(
  options: ServeOptions,
): Promise<{ server: Server | null; error: Error | null }>;
